import { StandeeTheme } from "@/types";

export const STANDEE_THEMES: StandeeTheme[] = [
  {
    id: "sunburn-slate",
    name: "Sunburn Slate",
    background: "#ffffff",
    foreground: "#152935",
    accent: "#698ea2",
    badgeBg: "#152935",
    badgeText: "#ffffff",
    qrBg: "#ccd5d220",
    qrFg: "#152935",
    border: "border-4 border-[#e4a576]",
    description: "Corporate Indian fintech with navy and warm amber accents.",
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber Dark",
    background: "#09090b",
    foreground: "#ffffff",
    accent: "#00FF66",
    badgeBg: "#00FF66",
    badgeText: "#000000",
    qrBg: "#18181b",
    qrFg: "#00FF66",
    border: "border-4 border-[#00FF66]",
    description: "High-contrast dark neon for modern cafes, salons, and gaming hubs.",
  },
  {
    id: "festive-gold",
    name: "Festive Gold",
    background: "#fffaf0",
    foreground: "#800020",
    accent: "#b8860b",
    badgeBg: "#800020",
    badgeText: "#ffd700",
    qrBg: "#ffffff",
    qrFg: "#800020",
    border: "border-4 border-[#ffd700]",
    description: "Royal maroon & gold frame suited for festive sales and retail.",
  },
  {
    id: "minimal-bw",
    name: "Minimal Monochrome",
    background: "#ffffff",
    foreground: "#000000",
    accent: "#52525b",
    badgeBg: "#000000",
    badgeText: "#ffffff",
    qrBg: "#f4f4f5",
    qrFg: "#000000",
    border: "border-4 border-black",
    description: "Ultra-clean black & white design for budget black-and-white printing.",
  },
  {
    id: "cafe-premium",
    name: "Cafe Premium",
    background: "#fefae0",
    foreground: "#283618",
    accent: "#dda15e",
    badgeBg: "#606c38",
    badgeText: "#fefae0",
    qrBg: "#ffffff",
    qrFg: "#283618",
    border: "border-4 border-[#bc6c25]",
    description: "Earthy artisan theme for cafes, bakeries, and cloud kitchens.",
  },
  {
    id: "salon-luxury",
    name: "Salon Luxury",
    background: "#1c1917",
    foreground: "#fafaf9",
    accent: "#f59e0b",
    badgeBg: "#292524",
    badgeText: "#fbbf24",
    qrBg: "#292524",
    qrFg: "#ffffff",
    border: "border-4 border-[#f59e0b]",
    description: "Dark luxury styling for premium spas, beauty parlours, and studios.",
  },
  {
    id: "kirana-classic",
    name: "Kirana Classic",
    background: "#ffffff",
    foreground: "#1e3a8a",
    accent: "#dc2626",
    badgeBg: "#1e3a8a",
    badgeText: "#ffffff",
    qrBg: "#eff6ff",
    qrFg: "#1e3a8a",
    border: "border-4 border-[#dc2626]",
    description: "Bright, readable high-visibility theme for grocery and general stores.",
  },
  {
    id: "street-vendor",
    name: "Street Vendor Bold",
    background: "#ffffff",
    foreground: "#000000",
    accent: "#ea580c",
    badgeBg: "#ea580c",
    badgeText: "#ffffff",
    qrBg: "#fff7ed",
    qrFg: "#000000",
    border: "border-8 border-[#ea580c]",
    description: "Massive QR focus and high-contrast alert borders for stalls and food carts.",
  },
];
